[tasks.build_latest]
description = "Build aoc_latest"
command = "cargo"
args = ["build", "-p", "aoc_latest", "--release"]
workspace = false

[tasks.vtune]
description = "Run intel vTune"
dependencies = ["build_latest"]
script = '''
    rm -rf vtune_out
    sudo "c:/Program Files (x86)/Intel/oneAPI/vtune/latest/bin64/vtune.exe" -r vtune_out -collect hotspots -knob sampling-mode=hw -- target/release/aoc_latest.exe -r 10
    "c:/Program Files (x86)/Intel/oneAPI/vtune/latest/bin64/vtune-gui.exe" vtune_out
'''
workspace = false

[tasks.flamegraph]
description = "Generate flamegraph for aoc_latest"
install_crate = "flamegraph"
command = "sudo"
args = ["cargo", "flamegraph", "-p", "aoc_latest"]
workspace = false

[tasks.watch]
description = "watch for latest changes to a single solution file and recompile and run on changes"
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "--why", "-x", "run --release -p aoc_latest"]
workspace = false

[tasks.watch2]
description = "watch for latest changes to a single solution file and recompile and run on changes"
install_crate = "cargo-watch"
command = "cargo"
args = ["run", "--release", "-p", "aoc_latest"]
watch = true
workspace = false

[tasks.run_all]
description = "compile and run all solutions"
command = "cargo"
args = ["run", "--release", "-p", "aoc"]
workspace = false

[tasks.this_year]
description = "compile and run all solutions"
command = "cargo"
args = ["run", "--release", "-p", "aoc", "--", "-y2023"]
workspace = false

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_BACKTRACE = 0